# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import backtest_pb2 as backtest__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in backtest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BacktestEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunBacktest = channel.unary_unary(
                '/backtest.BacktestEngine/RunBacktest',
                request_serializer=backtest__pb2.BacktestRequest.SerializeToString,
                response_deserializer=backtest__pb2.BacktestResult.FromString,
                _registered_method=True)
        self.StreamBars = channel.unary_stream(
                '/backtest.BacktestEngine/StreamBars',
                request_serializer=backtest__pb2.StreamRequest.SerializeToString,
                response_deserializer=backtest__pb2.Bar.FromString,
                _registered_method=True)
        self.SubmitOrder = channel.unary_unary(
                '/backtest.BacktestEngine/SubmitOrder',
                request_serializer=backtest__pb2.Order.SerializeToString,
                response_deserializer=backtest__pb2.Fill.FromString,
                _registered_method=True)


class BacktestEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=backtest__pb2.BacktestRequest.FromString,
                    response_serializer=backtest__pb2.BacktestResult.SerializeToString,
            ),
            'StreamBars': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBars,
                    request_deserializer=backtest__pb2.StreamRequest.FromString,
                    response_serializer=backtest__pb2.Bar.SerializeToString,
            ),
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=backtest__pb2.Order.FromString,
                    response_serializer=backtest__pb2.Fill.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backtest.BacktestEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('backtest.BacktestEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BacktestEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backtest.BacktestEngine/RunBacktest',
            backtest__pb2.BacktestRequest.SerializeToString,
            backtest__pb2.BacktestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/backtest.BacktestEngine/StreamBars',
            backtest__pb2.StreamRequest.SerializeToString,
            backtest__pb2.Bar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backtest.BacktestEngine/SubmitOrder',
            backtest__pb2.Order.SerializeToString,
            backtest__pb2.Fill.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
