// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/backtest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	OrderSide_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backtest_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_proto_backtest_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{0}
}

type OrderStatus int32

const (
	OrderStatus_PENDING  OrderStatus = 0
	OrderStatus_FILLED   OrderStatus = 1
	OrderStatus_REJECTED OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "FILLED",
		2: "REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":  0,
		"FILLED":   1,
		"REJECTED": 2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backtest_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_backtest_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{1}
}

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	DateUnix      int64                  `protobuf:"varint,2,opt,name=date_unix,json=dateUnix,proto3" json:"date_unix,omitempty"`
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount        float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	AdjFactor     float64                `protobuf:"fixed64,9,opt,name=adj_factor,json=adjFactor,proto3" json:"adj_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_proto_backtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{0}
}

func (x *Bar) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Bar) GetDateUnix() int64 {
	if x != nil {
		return x.DateUnix
	}
	return 0
}

func (x *Bar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Bar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Bar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Bar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Bar) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Bar) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bar) GetAdjFactor() float64 {
	if x != nil {
		return x.AdjFactor
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,2,opt,name=side,proto3,enum=backtest.OrderSide" json:"side,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_backtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *Order) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Fill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,2,opt,name=side,proto3,enum=backtest.OrderSide" json:"side,omitempty"`
	FilledQty     float64                `protobuf:"fixed64,3,opt,name=filled_qty,json=filledQty,proto3" json:"filled_qty,omitempty"`
	FilledPrice   float64                `protobuf:"fixed64,4,opt,name=filled_price,json=filledPrice,proto3" json:"filled_price,omitempty"`
	Commission    float64                `protobuf:"fixed64,5,opt,name=commission,proto3" json:"commission,omitempty"`
	StampDuty     float64                `protobuf:"fixed64,6,opt,name=stamp_duty,json=stampDuty,proto3" json:"stamp_duty,omitempty"`
	Status        OrderStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=backtest.OrderStatus" json:"status,omitempty"`
	RejectReason  string                 `protobuf:"bytes,8,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_proto_backtest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{2}
}

func (x *Fill) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Fill) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *Fill) GetFilledQty() float64 {
	if x != nil {
		return x.FilledQty
	}
	return 0
}

func (x *Fill) GetFilledPrice() float64 {
	if x != nil {
		return x.FilledPrice
	}
	return 0
}

func (x *Fill) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *Fill) GetStampDuty() float64 {
	if x != nil {
		return x.StampDuty
	}
	return 0
}

func (x *Fill) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *Fill) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type BacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	InitCapital   float64                `protobuf:"fixed64,4,opt,name=init_capital,json=initCapital,proto3" json:"init_capital,omitempty"`
	Commission    float64                `protobuf:"fixed64,5,opt,name=commission,proto3" json:"commission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestRequest) Reset() {
	*x = BacktestRequest{}
	mi := &file_proto_backtest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestRequest) ProtoMessage() {}

func (x *BacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestRequest.ProtoReflect.Descriptor instead.
func (*BacktestRequest) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{3}
}

func (x *BacktestRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *BacktestRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BacktestRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *BacktestRequest) GetInitCapital() float64 {
	if x != nil {
		return x.InitCapital
	}
	return 0
}

func (x *BacktestRequest) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

type BacktestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnnualReturn  float64                `protobuf:"fixed64,1,opt,name=annual_return,json=annualReturn,proto3" json:"annual_return,omitempty"`
	MaxDrawdown   float64                `protobuf:"fixed64,2,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`
	SharpeRatio   float64                `protobuf:"fixed64,3,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"`
	WinRate       float64                `protobuf:"fixed64,4,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	AvgHoldDays   float64                `protobuf:"fixed64,5,opt,name=avg_hold_days,json=avgHoldDays,proto3" json:"avg_hold_days,omitempty"`
	TurnoverRate  float64                `protobuf:"fixed64,6,opt,name=turnover_rate,json=turnoverRate,proto3" json:"turnover_rate,omitempty"`
	CalmarRatio   float64                `protobuf:"fixed64,7,opt,name=calmar_ratio,json=calmarRatio,proto3" json:"calmar_ratio,omitempty"`
	TotalReturn   float64                `protobuf:"fixed64,8,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"`
	EquityCurve   []float64              `protobuf:"fixed64,9,rep,packed,name=equity_curve,json=equityCurve,proto3" json:"equity_curve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestResult) Reset() {
	*x = BacktestResult{}
	mi := &file_proto_backtest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestResult) ProtoMessage() {}

func (x *BacktestResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestResult.ProtoReflect.Descriptor instead.
func (*BacktestResult) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{4}
}

func (x *BacktestResult) GetAnnualReturn() float64 {
	if x != nil {
		return x.AnnualReturn
	}
	return 0
}

func (x *BacktestResult) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *BacktestResult) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *BacktestResult) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *BacktestResult) GetAvgHoldDays() float64 {
	if x != nil {
		return x.AvgHoldDays
	}
	return 0
}

func (x *BacktestResult) GetTurnoverRate() float64 {
	if x != nil {
		return x.TurnoverRate
	}
	return 0
}

func (x *BacktestResult) GetCalmarRatio() float64 {
	if x != nil {
		return x.CalmarRatio
	}
	return 0
}

func (x *BacktestResult) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *BacktestResult) GetEquityCurve() []float64 {
	if x != nil {
		return x.EquityCurve
	}
	return nil
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_backtest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{5}
}

func (x *StreamRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *StreamRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *StreamRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

var File_proto_backtest_proto protoreflect.FileDescriptor

const file_proto_backtest_proto_rawDesc = "" +
	"\n" +
	"\x14proto/backtest.proto\x12\bbacktest\"\xd9\x01\n" +
	"\x03Bar\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\tdate_unix\x18\x02 \x01(\x03R\bdateUnix\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\x01R\x06volume\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"adj_factor\x18\t \x01(\x01R\tadjFactor\"z\n" +
	"\x05Order\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12'\n" +
	"\x04side\x18\x02 \x01(\x0e2\x13.backtest.OrderSideR\x04side\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"\x9c\x02\n" +
	"\x04Fill\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12'\n" +
	"\x04side\x18\x02 \x01(\x0e2\x13.backtest.OrderSideR\x04side\x12\x1d\n" +
	"\n" +
	"filled_qty\x18\x03 \x01(\x01R\tfilledQty\x12!\n" +
	"\ffilled_price\x18\x04 \x01(\x01R\vfilledPrice\x12\x1e\n" +
	"\n" +
	"commission\x18\x05 \x01(\x01R\n" +
	"commission\x12\x1d\n" +
	"\n" +
	"stamp_duty\x18\x06 \x01(\x01R\tstampDuty\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.backtest.OrderStatusR\x06status\x12#\n" +
	"\rreject_reason\x18\b \x01(\tR\frejectReason\"\xa8\x01\n" +
	"\x0fBacktestRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12!\n" +
	"\finit_capital\x18\x04 \x01(\x01R\vinitCapital\x12\x1e\n" +
	"\n" +
	"commission\x18\x05 \x01(\x01R\n" +
	"commission\"\xc8\x02\n" +
	"\x0eBacktestResult\x12#\n" +
	"\rannual_return\x18\x01 \x01(\x01R\fannualReturn\x12!\n" +
	"\fmax_drawdown\x18\x02 \x01(\x01R\vmaxDrawdown\x12!\n" +
	"\fsharpe_ratio\x18\x03 \x01(\x01R\vsharpeRatio\x12\x19\n" +
	"\bwin_rate\x18\x04 \x01(\x01R\awinRate\x12\"\n" +
	"\ravg_hold_days\x18\x05 \x01(\x01R\vavgHoldDays\x12#\n" +
	"\rturnover_rate\x18\x06 \x01(\x01R\fturnoverRate\x12!\n" +
	"\fcalmar_ratio\x18\a \x01(\x01R\vcalmarRatio\x12!\n" +
	"\ftotal_return\x18\b \x01(\x01R\vtotalReturn\x12!\n" +
	"\fequity_curve\x18\t \x03(\x01R\vequityCurve\"c\n" +
	"\rStreamRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate*\x1e\n" +
	"\tOrderSide\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*4\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\n" +
	"\n" +
	"\x06FILLED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x022\xbc\x01\n" +
	"\x0eBacktestEngine\x12B\n" +
	"\vRunBacktest\x12\x19.backtest.BacktestRequest\x1a\x18.backtest.BacktestResult\x126\n" +
	"\n" +
	"StreamBars\x12\x17.backtest.StreamRequest\x1a\r.backtest.Bar0\x01\x12.\n" +
	"\vSubmitOrder\x12\x0f.backtest.Order\x1a\x0e.backtest.FillB2Z0github.com/parsedong/stock/backtest-engine/protob\x06proto3"

var (
	file_proto_backtest_proto_rawDescOnce sync.Once
	file_proto_backtest_proto_rawDescData []byte
)

func file_proto_backtest_proto_rawDescGZIP() []byte {
	file_proto_backtest_proto_rawDescOnce.Do(func() {
		file_proto_backtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backtest_proto_rawDesc), len(file_proto_backtest_proto_rawDesc)))
	})
	return file_proto_backtest_proto_rawDescData
}

var file_proto_backtest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_backtest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_backtest_proto_goTypes = []any{
	(OrderSide)(0),          // 0: backtest.OrderSide
	(OrderStatus)(0),        // 1: backtest.OrderStatus
	(*Bar)(nil),             // 2: backtest.Bar
	(*Order)(nil),           // 3: backtest.Order
	(*Fill)(nil),            // 4: backtest.Fill
	(*BacktestRequest)(nil), // 5: backtest.BacktestRequest
	(*BacktestResult)(nil),  // 6: backtest.BacktestResult
	(*StreamRequest)(nil),   // 7: backtest.StreamRequest
}
var file_proto_backtest_proto_depIdxs = []int32{
	0, // 0: backtest.Order.side:type_name -> backtest.OrderSide
	0, // 1: backtest.Fill.side:type_name -> backtest.OrderSide
	1, // 2: backtest.Fill.status:type_name -> backtest.OrderStatus
	5, // 3: backtest.BacktestEngine.RunBacktest:input_type -> backtest.BacktestRequest
	7, // 4: backtest.BacktestEngine.StreamBars:input_type -> backtest.StreamRequest
	3, // 5: backtest.BacktestEngine.SubmitOrder:input_type -> backtest.Order
	6, // 6: backtest.BacktestEngine.RunBacktest:output_type -> backtest.BacktestResult
	2, // 7: backtest.BacktestEngine.StreamBars:output_type -> backtest.Bar
	4, // 8: backtest.BacktestEngine.SubmitOrder:output_type -> backtest.Fill
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_backtest_proto_init() }
func file_proto_backtest_proto_init() {
	if File_proto_backtest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backtest_proto_rawDesc), len(file_proto_backtest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backtest_proto_goTypes,
		DependencyIndexes: file_proto_backtest_proto_depIdxs,
		EnumInfos:         file_proto_backtest_proto_enumTypes,
		MessageInfos:      file_proto_backtest_proto_msgTypes,
	}.Build()
	File_proto_backtest_proto = out.File
	file_proto_backtest_proto_goTypes = nil
	file_proto_backtest_proto_depIdxs = nil
}
