// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/backtest.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BacktestEngine_RunBacktest_FullMethodName = "/backtest.BacktestEngine/RunBacktest"
	BacktestEngine_StreamBars_FullMethodName  = "/backtest.BacktestEngine/StreamBars"
	BacktestEngine_SubmitOrder_FullMethodName = "/backtest.BacktestEngine/SubmitOrder"
)

// BacktestEngineClient is the client API for BacktestEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BacktestEngineClient interface {
	RunBacktest(ctx context.Context, in *BacktestRequest, opts ...grpc.CallOption) (*BacktestResult, error)
	StreamBars(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bar], error)
	SubmitOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Fill, error)
}

type backtestEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewBacktestEngineClient(cc grpc.ClientConnInterface) BacktestEngineClient {
	return &backtestEngineClient{cc}
}

func (c *backtestEngineClient) RunBacktest(ctx context.Context, in *BacktestRequest, opts ...grpc.CallOption) (*BacktestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BacktestResult)
	err := c.cc.Invoke(ctx, BacktestEngine_RunBacktest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestEngineClient) StreamBars(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bar], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BacktestEngine_ServiceDesc.Streams[0], BacktestEngine_StreamBars_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Bar]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BacktestEngine_StreamBarsClient = grpc.ServerStreamingClient[Bar]

func (c *backtestEngineClient) SubmitOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Fill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fill)
	err := c.cc.Invoke(ctx, BacktestEngine_SubmitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BacktestEngineServer is the server API for BacktestEngine service.
// All implementations must embed UnimplementedBacktestEngineServer
// for forward compatibility.
type BacktestEngineServer interface {
	RunBacktest(context.Context, *BacktestRequest) (*BacktestResult, error)
	StreamBars(*StreamRequest, grpc.ServerStreamingServer[Bar]) error
	SubmitOrder(context.Context, *Order) (*Fill, error)
	mustEmbedUnimplementedBacktestEngineServer()
}

// UnimplementedBacktestEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBacktestEngineServer struct{}

func (UnimplementedBacktestEngineServer) RunBacktest(context.Context, *BacktestRequest) (*BacktestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBacktest not implemented")
}
func (UnimplementedBacktestEngineServer) StreamBars(*StreamRequest, grpc.ServerStreamingServer[Bar]) error {
	return status.Error(codes.Unimplemented, "method StreamBars not implemented")
}
func (UnimplementedBacktestEngineServer) SubmitOrder(context.Context, *Order) (*Fill, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedBacktestEngineServer) mustEmbedUnimplementedBacktestEngineServer() {}
func (UnimplementedBacktestEngineServer) testEmbeddedByValue()                        {}

// UnsafeBacktestEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BacktestEngineServer will
// result in compilation errors.
type UnsafeBacktestEngineServer interface {
	mustEmbedUnimplementedBacktestEngineServer()
}

func RegisterBacktestEngineServer(s grpc.ServiceRegistrar, srv BacktestEngineServer) {
	// If the following call panics, it indicates UnimplementedBacktestEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BacktestEngine_ServiceDesc, srv)
}

func _BacktestEngine_RunBacktest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BacktestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestEngineServer).RunBacktest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BacktestEngine_RunBacktest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestEngineServer).RunBacktest(ctx, req.(*BacktestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BacktestEngine_StreamBars_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BacktestEngineServer).StreamBars(m, &grpc.GenericServerStream[StreamRequest, Bar]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BacktestEngine_StreamBarsServer = grpc.ServerStreamingServer[Bar]

func _BacktestEngine_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestEngineServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BacktestEngine_SubmitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestEngineServer).SubmitOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

// BacktestEngine_ServiceDesc is the grpc.ServiceDesc for BacktestEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BacktestEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backtest.BacktestEngine",
	HandlerType: (*BacktestEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBacktest",
			Handler:    _BacktestEngine_RunBacktest_Handler,
		},
		{
			MethodName: "SubmitOrder",
			Handler:    _BacktestEngine_SubmitOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBars",
			Handler:       _BacktestEngine_StreamBars_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/backtest.proto",
}
